import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  let header = (
    <header className="flex items-center justify-between p-4 bg-slate-50 text-slate-600">
      <Link href={"/"}>
        <div >
          <h1 className="text-2xl font-black">The<span className="text-red-500">Rolling</span><span className="font-black text-blue-500">Stones</span><span className="font-black text-slate-600">Blog</span></h1>
        </div>
      </Link>
      
      <nav>
        <ul className="flex space-x-4">
          <li>
            <Link href="/" className="hover:underline">
              Home
            </Link>
          </li>
          <li>
            <Link href="/post" className="hover:underline">
              Posts
            </Link>
          </li>
        </ul>
      </nav>
    </header>
  );

  let footer = (
    <footer className="p-4 bg-gray-800 text-white py-24">
      <p className="text-center">Helio Sales Jr. © 2024</p>
    </footer>
  );
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
